### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-3-Tiholiz-Igor** [UMSF-K13-3-Tiholiz-Igor/K13-3-Tiholiz-MainProject#1]
[Отчет.docx](https://github.com/UMSF-K13-3-Tiholiz-Igor/K13-3-Tiholiz-MainProject/files/252461/default.docx)

**Comment by Smoktii** [comment]
Все ОК.

**Comment by Smoktii** [comment]
Нужно назначить на меня ишью!

**Comment by Smoktii** [comment]
все корректно
